

SELECT*FROM DBO.ALUNO; --AQUI VISUALIZA TODA TABELA ALUNO

SELECT * FROM  DBO.ALUNO WHERE ID = 2  --AQUI VISUALIZA UM CAMPO ESPECÍFICO
UPDATE ALUNO SET nome = 'Arthur' WHERE id = 2 --  aqui altera o tabela aluno, na coluna nome na linha ID 2
DELETE FROM DBO.ALUNO WHERE ID = 2; -- AQUI DELETA UM REGISTRO CUJO ID É 2


SELECT*FROM DBO.ALUNO_DISCIPLINA;


SELECT*FROM DBO.CURSO;

SELECT*FROM DBO.CURSO_DISCIPLINA;

SELECT*FROM DBO.DEPARTAMENTO;

SELECT*FROM DBO.DEPARTAMENTO_FUNCIONARIO;

SELECT*FROM DBO.DISCIPLINA;

SELECT*FROM DBO.ENDERECO;

SELECT*FROM DBO.FUNCIONARIO;

SELECT*FROM DBO.MATRICULA;

SELECT*FROM DBO.PROFESSOR;

SELECT*FROM DBO.PROFESSOR_DISCIPLINA;

SELECT*FROM DBO.TELEFONE;

