
--INSERT INTO DBO.TELEFONE
--VALUES ('TIPO A ou D OU F, ALUNO,DEPARTAMENTO,FUNCIONARIO', 'NUMERO DO TELEFONE COM DDD E SEM ESPAÇOS');

INSERT INTO DBO.TELEFONE VALUES ('A', '83911111111');
INSERT INTO DBO.TELEFONE VALUES ('A', '83922222222');
INSERT INTO DBO.TELEFONE VALUES ('A', '83933333333');
INSERT INTO DBO.TELEFONE VALUES ('A', '83944444444');
INSERT INTO DBO.TELEFONE VALUES ('A', '83955555555');
INSERT INTO DBO.TELEFONE VALUES ('A', '83966666666');
INSERT INTO DBO.TELEFONE VALUES ('A', '83977777777');
INSERT INTO DBO.TELEFONE VALUES ('A', '83988888888');
INSERT INTO DBO.TELEFONE VALUES ('A', '83999999999');
INSERT INTO DBO.TELEFONE VALUES ('A', '83999888777');

INSERT INTO DBO.TELEFONE VALUES ('F', '83988111111');
INSERT INTO DBO.TELEFONE VALUES ('F', '83988222222');
INSERT INTO DBO.TELEFONE VALUES ('F', '83988333333');
INSERT INTO DBO.TELEFONE VALUES ('F', '83988444444');
INSERT INTO DBO.TELEFONE VALUES ('F', '83988555555');
INSERT INTO DBO.TELEFONE VALUES ('F', '83988666666');
INSERT INTO DBO.TELEFONE VALUES ('F', '83988777777');
INSERT INTO DBO.TELEFONE VALUES ('F', '83999888888');
INSERT INTO DBO.TELEFONE VALUES ('F', '83988999999');
INSERT INTO DBO.TELEFONE VALUES ('F', '83985555999');

INSERT INTO DBO.TELEFONE VALUES ('D', '83988777111');
INSERT INTO DBO.TELEFONE VALUES ('D', '83999888222');
INSERT INTO DBO.TELEFONE VALUES ('D', '83988999333');



--INSERT INTO DBO.ENDERECO
--VALUES ('TIPO A ou F, ALUNO, FUNCIONARIO', 'PAÍS', 'ESTADO', 'CIDADE', 'BAIRRO', 'LOGRADOURO', 'NUMERO', 'CEP COM 8 DIGITOS SEM ESPACO');

INSERT INTO DBO.ENDERECO VALUES ('A', 'Brasil', 'PB', 'João Pessoa', 'Bessa', 'AV Beira Mar', 101, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A', 'Brasil', 'PB', 'João Pessoa', 'Bessa', 'AV Mar do sul', 1010, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A',  'Brasil', 'PB', 'João Pessoa', 'Bessa', 'AV Beira Mar', 310, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A',  'Brasil', 'PB', 'João Pessoa', 'Estados', 'AV Goiás', 2001, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A',  'Brasil', 'PB', 'João Pessoa', 'Estados', 'AV Pará', 554, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A',  'Brasil', 'PB', 'João Pessoa', 'Estados', 'AV Mato grosso', 5050, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A',  'Brasil', 'PB', 'João Pessoa', 'Bancarios', 'Rua Bancario Sergio guerra', 201, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A',  'Brasil', 'PB', 'João Pessoa', 'Bancarios', 'Rua Bancario Sergio guerra', 5101, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A',  'Brasil', 'PB', 'João Pessoa', 'Bancarios', 'Rua Maria Lianza', 201, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('A',  'Brasil', 'PB', 'João Pessoa', 'Valentina', 'Rua Santa Luzia', 100, 58000000);


INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Bancarios', 'Rua Bancario Sergio guerra', 6541, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Bancarios', 'Rua Bancario Sergio guerra', 3256, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Bancarios', 'Rua Bancario Sergio guerra', 201, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Bessa', 'Rua do sol', 1001, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Bessa', 'Rua do sol', 654, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Manaíra', 'Av Esperança', 100, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Manaíra', 'Rua Princesa Isabel', 100, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Manaíra', 'Rua Manaíra', 100, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Manaíra', 'Rua Príncipe de Gales', 100, 58000000);
INSERT INTO DBO.ENDERECO VALUES ('F',  'Brasil', 'PB', 'João Pessoa', 'Jaguaribe', 'Rua Maria Sales', 80, 58000000);



SELECT*FROM DBO.TELEFONE;
SELECT*FROM DBO.ENDERECO;


--INSERT INTO DBO.ALUNO
--VALUES ('NOME', 'nome social', 'CPF sem espaco ou hifem', 'tem deficiencia', 'modo de entrada: E ou V ou T - Enem, Vestibular ou TRansferencia','historico escolar', 'finacimaneto: P ou F ou U - PROPRIO, Fies OU pRO uni', id endereco, id telefone, 'sexo: M masculino, F feminino', 'data de nascimento');

INSERT INTO DBO.ALUNO VALUES ('Maria Eduarda', 'NULL', '36526512547', 'NULL', 'E','Escola pública', 'P', 1, 1, 'F', '1995-10-15');
INSERT INTO DBO.ALUNO VALUES ('Mariana', 'NULL', '78965412365', 'NULL', 'E','Escola pública', 'P', 2, 2, 'F', '1998-11-21');
INSERT INTO DBO.ALUNO VALUES ('Juliana', 'NULL', '98532658721', 'NULL', 'E','Escola pública', 'F', 3, 3, 'F', '2001-11-21');
INSERT INTO DBO.ALUNO VALUES ('Cecília', 'NULL', '25415458741', 'NULL', 'V','Escola pública', 'F', 4, 4, 'F', '2001-11-21');
INSERT INTO DBO.ALUNO VALUES ('Marta', 'NULL', '12315458741', 'NULL', 'V','Escola privada', 'F', 5, 5, 'F', '2000-06-12');
INSERT INTO DBO.ALUNO VALUES ('CAIO', 'NULL', '32165496325', 'NULL', 'E','Escola privda', 'P', 6, 6, 'M', '2001-11-21');
INSERT INTO DBO.ALUNO VALUES ('LUIZ', 'NULL', '56836530201', 'NULL', 'V','Escola pública', 'F', 7, 7, 'M', '1999-03-10');
INSERT INTO DBO.ALUNO VALUES ('MARCOS', 'NULL', '02536914898', 'NULL', 'T','Escola pública', 'P', 8, 8, 'M', '1997-05-03');
INSERT INTO DBO.ALUNO VALUES ('JONAS', 'NULL', '85430236501', 'NULL', 'T','Escola privadaa', 'p', 9, 9, 'M', '1999-09-20');
INSERT INTO DBO.ALUNO VALUES ('JONAS', 'NULL', '85430236501', 'NULL', 'T','Escola privadaa', 'p', 9, 9, 'M', '1999-09-20');
INSERT INTO DBO.ALUNO VALUES ('JOSE', 'NULL', '23650236501', 'NULL', 'T','Escola privadaa', 'p', 19, 22, 'M', '1999-09-20');

SELECT*FROM DBO.ALUNO;

--INSERT INTO DBO.DEPARTAMENTO VALUES ('nome', 'descricao', 'cursos que integram');
INSERT INTO DBO.DEPARTAMENTO VALUES ('INFORMATICA', 'Cursos de tecnocologia', 'Sistemas para internet, sistemas de Informação');
INSERT INTO DBO.DEPARTAMENTO VALUES ('CIENCIAS DA SAUDE', 'Cursos de saúde e a´reas afins', 'Enfermagem, Fisioterapia, Medicina');
INSERT INTO DBO.DEPARTAMENTO VALUES ('CIENCIAS SOCIAIS APLICADAS', 'Cursos de cIENCIAS APLICASDAS A SOCIEDADE', 'CONTABILIDADE');

SELECT*FROM DBO.DEPARTAMENTO;

--INSERT INTO DBO.CURSO
--VALUES ('nome', 'GRADE CURRICULAR', 'B ou T ou P - BACHARELADO, TECNOLOGO E POS-GRADUACAO', 'id do departamento');


INSERT INTO DBO.CURSO VALUES ('sistemas para inernet', '25 disciplinas ', 'T', 1);
INSERT INTO DBO.CURSO VALUES ('sistemas DA INFORMAÇÃO', '60 disciplinas ', 'B', 1);
INSERT INTO DBO.CURSO VALUES ('CIEMCIA DA COMPUTAÇÃO', '80 disciplinas', 'B', 1);

INSERT INTO DBO.CURSO VALUES ('ENFERMAGEM', '120 disciplinas', 'B', 2);
INSERT INTO DBO.CURSO VALUES ('FISIOTERAPIA', '120 disciplinas', 'B', 2);
INSERT INTO DBO.CURSO VALUES ('MEDICINA', '120 disciplinas', 'B', 2);

INSERT INTO DBO.CURSO VALUES ('CIENCIAS CONTABEIS', '120 disciplinas', 'B', 3);

SELECT*FROM DBO.CURSO;

--INSERT INTO DBO.DISCIPLINA VALUES ('nome', ' ementa', 'carga horaria');
INSERT INTO DBO.DISCIPLINA VALUES ('BANCO DE DADOS', 'CRIAÇÃO EMANITPILAÇÃO DE BANCO DE DADOS', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('REDES D COMPUTADORES', 'CONHECIENTO BASICO DE RSDES', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('FRONT END 1', 'HTML E CSS', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('FRONT END 2', 'JS', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('INTRODUÇÃO A PROGRAMAÇÃO', 'JAVA', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('LOGIA MATEMATICA', 'CONTEUO DE LOGICA', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('ALGORITMO E LOGICA DE PROGRAMAÇÃO', 'PRODUÇÃO DE ALGORTIMO E COMPREENSOA DE LOGICA', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('BANCO DE DADOS 2', 'USO DE SGBD', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('ESTRUTUR DE DADOS', 'COM PYTHON', 70);
INSERT INTO DBO.DISCIPLINA VALUES ('EMPREENDDORISMO', 'COM PYTHON', 70);

SELECT*FROM DBO.DISCIPLINA;

--INSERT INTO ALUNO_DISCIPLINA VALUES ('SITUACAO: A parovado, R reprovado,  C cursando', ID ALUNO, ID DISCIPLINA);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 1, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 1, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 1, 3);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 1, 4);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 1, 5);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 1, 6);

INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 2, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 2, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 2, 3);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 2, 4);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 2, 5);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 2, 6);


INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 3, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 3, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 3, 3);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 3, 4);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 3, 5);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 3, 6);


INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 4, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 4, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 4, 3);

INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 5, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 5, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 5, 3);


INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 6, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 6, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 6, 3);

INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 7, 4);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 7, 5);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 7, 6);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 7, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 7, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 7, 3);


INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 8, 4);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 8, 5);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 8, 6);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 8, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 8, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 8, 3);


INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 9, 4);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 9, 5);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 9, 6);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 9, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 9, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 9, 3);

INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 9, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 9, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 9, 3);


INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 10, 4);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 10, 5);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 10, 6);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 10, 1);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 10, 2);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 10, 3);

INSERT INTO ALUNO_DISCIPLINA VALUES ('R', 10, 7);
INSERT INTO ALUNO_DISCIPLINA VALUES ('R', 8, 7);
INSERT INTO ALUNO_DISCIPLINA VALUES ('R', 9, 7);

INSERT INTO ALUNO_DISCIPLINA VALUES ('R', 1, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('R', 2, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('R', 3, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('R', 4, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('R', 5, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 6, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 7, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('C', 8, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 9, 10);
INSERT INTO ALUNO_DISCIPLINA VALUES ('A', 10, 10);



SELECT*FROM DBO.ALUNO_DISCIPLINA;

--INSERT INTO MATRICULA VALUES ('DATA DA MATRICULA', ID ALUNO, ID CURSO, ID DISCIPLINA);


INSERT INTO MATRICULA VALUES ('2022-02-10', 1, 1, 4);
INSERT INTO MATRICULA VALUES ('2022-02-10', 1, 1, 5);
INSERT INTO MATRICULA VALUES ('2022-02-10', 1, 1, 6);

INSERT INTO MATRICULA VALUES ('2022-02-11',  2, 1, 4);
INSERT INTO MATRICULA VALUES ('2022-02-11',  2, 1, 5);
INSERT INTO MATRICULA VALUES ('2022-02-11',  2, 1, 6);

INSERT INTO MATRICULA VALUES ('2022-02-11',  3, 1, 4);
INSERT INTO MATRICULA VALUES ('2022-02-11',  3, 1, 5);
INSERT INTO MATRICULA VALUES ('2022-02-11',  3, 1, 6);

INSERT INTO MATRICULA VALUES ('2022-02-11',  7, 1, 4);
INSERT INTO MATRICULA VALUES ('2022-02-11',  7, 1, 5);
INSERT INTO MATRICULA VALUES ('2022-02-11',  7, 1, 6);

INSERT INTO MATRICULA VALUES ('2022-02-11',  4, 1, 1);
INSERT INTO MATRICULA VALUES ('2022-02-11',  4, 1, 2);
INSERT INTO MATRICULA VALUES ('2022-02-11',  4, 1, 3);

INSERT INTO MATRICULA VALUES ('2022-02-11', 5, 1, 1);
INSERT INTO MATRICULA VALUES ('2022-02-11', 5, 1, 2);
INSERT INTO MATRICULA VALUES ('2022-02-11', 5, 1, 3);

INSERT INTO MATRICULA VALUES ('2022-02-11', 6, 1, 1);
INSERT INTO MATRICULA VALUES ('2022-02-11', 6, 1, 2);
INSERT INTO MATRICULA VALUES ('2022-02-11', 6, 1, 3);

INSERT INTO MATRICULA VALUES ('2022-02-11', 8, 1, 4);
INSERT INTO MATRICULA VALUES ('2022-02-11', 8, 1, 5);
INSERT INTO MATRICULA VALUES ('2022-02-11', 8, 1, 6);

INSERT INTO MATRICULA VALUES ('2022-02-11', 9, 1, 4);
INSERT INTO MATRICULA VALUES ('2022-02-11', 9, 1, 5);
INSERT INTO MATRICULA VALUES ('2022-02-11', 9, 1, 6);

INSERT INTO MATRICULA VALUES ('2022-02-11', 6, 1, 10);
INSERT INTO MATRICULA VALUES ('2022-02-11', 7, 1, 10);
INSERT INTO MATRICULA VALUES ('2022-02-11', 8, 1, 10);

INSERT INTO MATRICULA VALUES ('2022-02-11', 10, 1, 4);
INSERT INTO MATRICULA VALUES ('2022-02-11', 10,  1, 5);
INSERT INTO MATRICULA VALUES ('2022-02-11', 110, 1, 6);

SELECT*FROM DBO.MATRICULA;

--INSERT INTO DBO.FUNCIONARIO VALUES ('tipo: P professor ou O outro', 'NOME', 'nome social', 'sexo: M masculino F feminino', 'data de nascimento', 'data de contratação', 'email', 'CPF sem espaco ou hifem', 'salario', id endereco, id telefone);
INSERT INTO DBO.FUNCIONARIO VALUES ('P', 'ANA', 'ANA', 'F', '1976-06-21', '2020-02-10', 'ana@faculdade.edu.br', '25896375321', '12563.56',10 , 10);
INSERT INTO DBO.FUNCIONARIO VALUES ('P', 'ANTONIO', NULL, 'M', '1972-03-12', '2020-02-10', 'tony@faculdade.edu.br', '56532575321', '18563.56',11 , 11);
INSERT INTO DBO.FUNCIONARIO VALUES ('P', 'PAULO', NULL, 'M', '1985-12-22', '2020-02-10', 'paulo@faculdade.edu.br', '25632510214', '12563.56',12 , 12);
INSERT INTO DBO.FUNCIONARIO VALUES ('P', 'ARTHUR', NULL, 'M', '1994-05-22', '2020-02-10', 'arthur@faculdade.edu.br', '10332510214', '22563.56',13 , 13);
INSERT INTO DBO.FUNCIONARIO VALUES ('P', 'LUCIA', NULL, 'F', '1979-08-02', '2020-02-10', 'lu@faculdade.edu.br', '08532510214', '18563.56',14 , 14);
INSERT INTO DBO.FUNCIONARIO VALUES ('P', 'MAURO', NULL, 'M', '1973-09-07', '2020-02-10', 'mauro@faculdade.edu.br', '18532510214', '12563.56',15 , 15);
INSERT INTO DBO.FUNCIONARIO VALUES ('O', 'JOAO', NULL, 'M', '1995-12-22', '2020-02-10', 'joao@faculdade.edu.br', '33332510214', '1256.56',16 , 16);
INSERT INTO DBO.FUNCIONARIO VALUES ('O', 'Mateus', NULL, 'M', '2001-10-03', '2020-02-10', 'mateus@faculdade.edu.br', '21232510214', '1256.56',17 , 17);
INSERT INTO DBO.FUNCIONARIO VALUES ('O', 'Marcos', NULL, 'M', '2000-07-03', '2020-02-10', 'marcos@faculdade.edu.br', '97232510214', '1256.56',18 , 18);
INSERT INTO DBO.FUNCIONARIO VALUES ('O', 'Lucas', NULL, 'M', '2001-10-03', '2020-02-10', 'mateus@faculdade.edu.br', '21232510214', '1256.56',20 , 20);

SELECT*FROM DBO.FUNCIONARIO;


--INSERT INTO DBO.PROFESSOR
--VALUES ('TITULAÇÃO: D doutor, M mestre, E especialista, G graduado', ID FUNCIONARIO);


INSERT INTO DBO.PROFESSOR VALUES ('D', 1);
INSERT INTO DBO.PROFESSOR VALUES ('M', 2);
INSERT INTO DBO.PROFESSOR VALUES ('D', 3);
INSERT INTO DBO.PROFESSOR VALUES ('M', 4);
INSERT INTO DBO.PROFESSOR VALUES ('E', 5);



SELECT*FROM DBO.PROFESSOR;
SELECT*FROM DBO.DISCIPLINA;


--INSERT INTO PROFESSOR_DISCIPLINA VALUES (ID PROFESSOR, ID DISCIPLINA);
INSERT INTO PROFESSOR_DISCIPLINA VALUES (1,9);
INSERT INTO PROFESSOR_DISCIPLINA VALUES (2,1);
INSERT INTO PROFESSOR_DISCIPLINA VALUES (3,2);
INSERT INTO PROFESSOR_DISCIPLINA VALUES (4,3);
INSERT INTO PROFESSOR_DISCIPLINA VALUES (5,6);
INSERT INTO PROFESSOR_DISCIPLINA VALUES (2,7);
INSERT INTO PROFESSOR_DISCIPLINA VALUES (3,8);
INSERT INTO PROFESSOR_DISCIPLINA VALUES (4,10);

SELECT*FROM DBO.PROFESSOR_DISCIPLINA;



--INSERT INTO DBO.CURSO_DISCIPLINA VALUES (ID CURSO, ID DICIPLINA);

INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,1);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,2);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,3);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,4);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,5);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,6);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,7);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,8);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,9);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (1,10);


INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,1);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,2);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,3);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,4);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,5);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,6);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,7);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,8);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,9);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (2,10);


INSERT INTO DBO.CURSO_DISCIPLINA VALUES (3,1);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (3,2);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (3,3);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (3,4);
INSERT INTO DBO.CURSO_DISCIPLINA VALUES (3,5);

SELECT*FROM DBO.CURSO_DISCIPLINA;

--INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('DATA DA INTEGRAÇÃO', ID DEPARTAMENTO, ID FUNCIONARIO);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-03-06', 1, 1);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-03-06', 1, 2);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-06-10', 1, 3);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-05-05', 1, 4);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-06-06', 1, 5);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-01-03', 1, 7);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-01-03', 1, 8);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-01-03', 1, 9);
INSERT INTO DEPARTAMENTO_FUNCIONARIO VALUES ('2022-01-03', 1, 10);

SELECT*FROM DBO.DEPARTAMENTO_FUNCIONARIO;

