USE UNIVERSIDADE;

--1 listar professores entre os funcionarios
SELECT * FROM FUNCIONARIO
WHERE TIPO = 'P' 


-- 2 Selecionar professores e salários entre R$10000.00 e R$20000.00?
SELECT A.NOME, A.SALARIO FROM (
SELECT * FROM FUNCIONARIO
WHERE TIPO = 'P') A
WHERE SALARIO BETWEEN 10000.00 AND 20000.00
ORDER BY NOME DESC;


--3 Quais os modos de entrada dos alunos?
SELECT DISTINCT MODO_ENTRADA FROM ALUNO;


-- 4 Quais alunos são do sexo feminino?
SELECT DISTINCT NOME FROM ALUNO
GROUP BY NOME, SEXO
HAVING SEXO = 'F';


--5 QUAIS NOMES, BAIRROS E TELEFONES DOS ALUNOS ?
SELECT A.NOME, E.BAIRRO, T.TELEFONE
FROM ALUNO AS A
INNER JOIN TELEFONE AS T
ON T.ID = A.ID_TELEFONE
INNER JOIN ENDERECO AS E
ON E.ID =A.ID_ENDERECO;

-- 6 QUAIS OS ALUNOS QUE ESTÃO CURSANDO A DISCIPLINA  BANCO DE DADOS?

SELECT A.NOME, D.NOME, AD.SITUACAO
FROM ALUNO AS A
INNER JOIN ALUNO_DISCIPLINA AS AD
ON A.ID = AD.ID_ALUNO
INNER JOIN DISCIPLINA AS D
ON D.ID = AD.ID_DISCIPLINA
WHERE SITUACAO  ='C' AND D.NOME = 'BANCO DE DADOS';


--7 lISTAS PROFESSORES, COM TUA TITULAÇÃO, SUA DISCIPLINA CORREPONDENTE E CARGA HORARIA

SELECT F.NOME, P.TITULACAO, D.NOME, D.CARGA_HORARIA
FROM FUNCIONARIO AS F
INNER JOIN PROFESSOR AS P
ON F.ID = P.ID_FUNCIONARIO
INNER JOIN PROFESSOR_DISCIPLINA AS PD
ON P.ID = PD.ID_PROFESSOR
INNER JOIN DISCIPLINA AS D
ON  D.ID = PD.ID_DISCIPLINA;


-- 8 QUANTOS FUNCIONARIOS TEM A FACULDADE?
SELECT COUNT (NOME) AS FUNCIONARIOS FROM FUNCIONARIO;

-- 9 QUAIS OS CURSOS POR DEPARTAMENTO?
SELECT D.NOME AS DEPARTAMENTO,C.NOME AS CURSO
FROM DEPARTAMENTO AS D
INNER JOIN CURSO AS C
ON D.ID = C.ID_DEPARTAMENTO;


--10 QUAIS AS DISCIPLINAS DO CURSO DE SISTEMA DA INFORMAÇÃO?

SELECT C.NOME, D.NOME, F.NOME
FROM CURSO AS C
INNER JOIN CURSO_DISCIPLINA AS CD
ON C.ID = CD.ID_CURSO
INNER JOIN DISCIPLINA AS D
ON D.ID = CD.ID_DISCIPLINA
INNER JOIN PROFESSOR_DISCIPLINA AS PD
ON PD.ID_DISCIPLINA = D.ID
INNER JOIN PROFESSOR AS P
ON P.ID = PD.ID_PROFESSOR
INNER JOIN FUNCIONARIO AS F
ON P.ID_FUNCIONARIO = F.ID;
